# Generated by Django 4.0.6 on 2022-08-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksLocations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('from_rack_number', models.IntegerField()),
                ('to_rack_number', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BooksDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('availability_status', models.BooleanField(default=True)),
                ('no_of_issue_copies', models.IntegerField()),
                ('rack_number', models.IntegerField()),
                ('popularity_rating', models.IntegerField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='LibraryAssistant.bookslocations')),
            ],
        ),
    ]
